spring:
  datasource:
    url: jdbc:mysql://193.112.187.136:3307/pouing_mdc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-mdc
      consumerGroup: CID_MDC
      producerGroup: PID_MDC