spring:
  datasource:
    url: jdbc:mysql://118.126.89.139:3306/pouing_omc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-omc
      consumerGroup: CID_OMC
      producerGroup: PID_OMC