spring:
  datasource:
    url: jdbc:mysql://193.112.187.136:3307/pouing_tpc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-tpc
      consumerGroup: CID_TPC
      producerGroup: PID_TPC