spring:
  datasource:
    url: jdbc:mysql://193.112.187.136:3307/pouing_opc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-opc
      consumerGroup: CID_OPC
      producerGroup: PID_OPC